version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
